branches:
  - name: main
    prerelease: false
    channel: latest
  - name: next
    prerelease: true
    channel: next

ci: true
debug: true
dryRun: false
tagFormat: '${version}'

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: 'conventionalcommits'
  - - "@semantic-release/release-notes-generator"
    - preset: 'conventionalcommits'
      writerOpts:
        groupBy: 'type'
        commitGroupsSort: 'title'
        commitsSort: 'header'
      linkCompare: true
      linkReferences: true
  - "@semantic-release/github"
