[supervisord]
nodaemon=true
logfile=/vein-server/logs/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=info

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=steam:steam

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:crond]
user=root
command=cron -f
stdout_syslog=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_syslog=true
stderr_logfile_maxbytes=0
redirect_stderr=true
autostart=true
autorestart=true
priority=10

[program:vein-bootstrap]
command=/vein-server/bin/vein-bootstrap.sh
priority=20
autostart=true
autorestart=false
startsecs=0
exitcodes=0
stdout_logfile=/vein-server/logs/bootstrap.log
stderr_logfile=/vein-server/logs/bootstrap.log
user=steam

[program:vein-updater]
command=/vein-server/bin/vein-updater.sh
priority=30
autostart=false
autorestart=false
startsecs=0
stdout_logfile=/vein-server/logs/updater.log
stderr_logfile=/vein-server/logs/updater.log
user=steam

[program:vein-server]
command=/vein-server/bin/vein-server.sh
priority=50
autostart=false
autorestart=false
startsecs=0
stdout_logfile=/vein-server/logs/server.log
stderr_logfile=/vein-server/logs/server.log
user=steam

[program:vein-backup]
command=/vein-server/bin/vein-backup.sh
priority=100
autostart=false
autorestart=false
startsecs=0
stopwaitsecs=600
stdout_logfile=/vein-server/logs/backup.log
stderr_logfile=/vein-server/logs/backup.log
user=steam

[program:vein-backup-and-restart]
command=/vein-server/bin/vein-backup.sh restart
priority=100
autostart=false
autorestart=false
startsecs=0
stopwaitsecs=600
stdout_logfile=/vein-server/logs/backup.log
stderr_logfile=/vein-server/logs/backup.log
user=steam

[program:vein-backup-and-update]
command=/vein-server/bin/vein-backup.sh update
priority=100
autostart=false
autorestart=false
startsecs=0
stopwaitsecs=600
stdout_logfile=/vein-server/logs/backup.log
stderr_logfile=/vein-server/logs/backup.log
user=steam
