[supervisord]
nodaemon=true
logfile=/vein-server/logs/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info
user=steam

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700
chown=steam:steam

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:vein-bootstrap]
command=/vein-server/bin/vein-bootstrap.sh
priority=20
autostart=true
autorestart=false
stdout_logfile=/vein-server/logs/bootstrap.log
stderr_logfile=/vein-server/logs/bootstrap.log
user=steam

[program:vein-updater]
command=/vein-server/bin/vein-updater.sh
priority=30
autostart=false
autorestart=false
stdout_logfile=/vein-server/logs/updater.log
stderr_logfile=/vein-server/logs/updater.log
user=steam

[program:vein-server]
command=/vein-server/bin/vein-server.sh
priority=50
autostart=false
autorestart=false
stdout_logfile=/vein-server/logs/server.log
stderr_logfile=/vein-server/logs/server.log
user=steam
