name: Build and Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './bin'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Lint Python with Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./config_from_env_vars"
          version: "~= 23.0"

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: vein-server:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    needs: lint-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: vein-server:test
          cache-from: type=gha

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python Unit Tests
        run: |
          cd config_from_env_vars
          python -m pytest test_main.py -v || echo "No tests found"
